plugins {
    id 'java'
}

group = 'br.furb.banco'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

// Configuração para o Gradle entender a estrutura do projeto
sourceSets {
    main {
        java {
            srcDirs = ['src/main']
        }
    }
    test {
        java {
            srcDirs = ['src/test']
        }
    }
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.2')

    testImplementation 'org.junit.jupiter:junit-jupiter-api'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'

    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()

    testLogging {
        // Mostrar saida
        showStandardStreams = true
        events "passed", "skipped", "failed"
    }
}